"""Constants for the Grouw Mower integration."""

from __future__ import annotations

from datetime import timedelta

from pygrouw.const import (
    APP_PACKAGE,
    DAYE_MODE_IDLE,
    DAYE_MODE_MOWING,
    DAYE_MODE_MOWING_ALTERNATE,
    DAYE_MODE_RETURNING,
    DAYE_MODE_STOPPED,
    DAYE_MOWING_MODE_CODES,
    DAYE_PRIMARY_CHARACTERISTIC_UUID,
    DAYE_PRIMARY_SERVICE_UUID,
    DAYE_SERVICE_UUIDS,
    DEFAULT_BLE_TIMEOUT,
    DEFAULT_CHUNK_DELAY,
    DEFAULT_NAME,
    DEFAULT_REQUESTED_MTU,
    READ_CHARACTERISTIC_UUID,
    SUPPORTED_LOCAL_NAME_PREFIXES,
    WRITE_CHARACTERISTIC_UUID,
)

DOMAIN = "grouw_ble_mower"

DEFAULT_UPDATE_INTERVAL = timedelta(seconds=30)
DEFAULT_BLE_BACKOFF_INTERVAL = timedelta(seconds=30)
STATUS_MAX_AGE = timedelta(seconds=60)
COMMAND_QUEUE_TIMEOUT = 10.0
COMMAND_MAX_QUEUE_AGE = 15.0
COMMAND_CONFIRM_TIMEOUT = 10.0
COMMAND_CONFIRM_INTERVAL = 1.0
HANDOFF_REFRESH_DELAY = 2.0

CONF_ADDRESS = "address"
CONF_PIN = "pin"

SERVICE_SEND_RAW_JSON = "send_raw_json"
SERVICE_CHANGE_PIN = "change_pin"
SERVICE_SET_MULTI_AREA = "set_multi_area"
SERVICE_SET_MOWER_SETTINGS = "set_mower_settings"
SERVICE_SET_WORK_TIMES = "set_work_times"
SERVICE_GET_MULTI_AREA = "get_multi_area"
SERVICE_GET_MOWER_SETTINGS = "get_mower_settings"
SERVICE_GET_WORK_TIMES = "get_work_times"
