"""Constants for the Grouw Mower integration."""
from __future__ import annotations

from datetime import timedelta

from pygrouw.const import (
    APP_PACKAGE,
    DAYE_MODE_IDLE,
    DAYE_MODE_MOWING,
    DAYE_MODE_MOWING_ALTERNATE,
    DAYE_MODE_RETURNING,
    DAYE_MODE_STOPPED,
    DAYE_MOWING_MODE_CODES,
    DAYE_PRIMARY_CHARACTERISTIC_UUID,
    DAYE_PRIMARY_SERVICE_UUID,
    DAYE_SERVICE_UUIDS,
    DEFAULT_BLE_TIMEOUT,
    DEFAULT_CHUNK_DELAY,
    DEFAULT_NAME,
    DEFAULT_REQUESTED_MTU,
    READ_CHARACTERISTIC_UUID,
    SUPPORTED_LOCAL_NAME_PREFIXES,
    WRITE_CHARACTERISTIC_UUID,
)

DOMAIN = "grouw_ble_mower"

DEFAULT_UPDATE_INTERVAL = timedelta(seconds=30)
DEFAULT_BLE_BACKOFF_INTERVAL = timedelta(seconds=30)

CONF_ADDRESS = "address"
CONF_PIN = "pin"

SERVICE_SEND_RAW_JSON = "send_raw_json"
